#!/usr/bin/env python3.9

# Account functions
from pw import Credentials, User

def create_account(name, email, uname, pw, user):
    return Credentials(name, email, uname, pw, user)

def save_account(account):
    account.save_account()

def generate_pw(length):
    return Credentials.generate_pw(length)

def set_pw(pw):
    return Credentials.set_pw(pw)

def display_accounts(user):
    Credentials.display_accounts(user)

def delete_account(account):
    account.delete_account()

# User functions
def create_user(fname, lname, uname, pw):
    return User(fname, lname, uname, pw)

def save_user(user):
    user.save_user()

def user_login(uname, pw):
    return user_login(uname, pw)

def delete_user(user):
    user.delete_user()

def display_users():
    return User.display_users()

# Main function
def main():
    print('Hello. Welcome to PassLock. Please log in or add new account to continue.')

    while True:
        print('What would you like to do? (Enter number to select)\n1. Create new user.\n2. Log in to an existing account.')
        choice = input('Enter choice: ')

        # Create new user.
        if choice == '1':
            print('\n\n***Create New User***\n')
            fname = input('First Name: ')
            lname = input('Last Name: ')
            username = input('Username: ')
            while True:
                print('Password: \n\t1. Autogenerate password.\n\t2. Enter custom password.')
                pw_input_choice = input('\tEnter choice: ')
                if pw_input_choice == '1':
                    pw_length = int(input('Enter desired autogenerated password length: '))
                    password = generate_pw(pw_length)
                    print(f'Autogenerated password is {password} \nYou will need to remember this.')
                    break
                elif pw_input_choice == '2':
                    pw_input = input('Enter password: ')
                    password = set_pw(pw_input)
                    break
                else:
                    print('Invalid choice. Try again.\n\n')

            create_user(fname, lname, username, password)
            print(f'\nNew user {fname} {lname} created.\n\n')
            continue
        


if __name__ == '__main__':
    main()